import { useEffect, useMemo, useRef, useState } from 'react';
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
import { useSearchParams } from '../../shared/router';
import { readScrollTop, scrollAppTo } from '../../shared/scroll';

import { catalogApi } from '../../shared/api/client';
import type { CatalogMeta } from '../../shared/api/types';
import { countActiveCatalogFilters } from '../../shared/catalog/logic.js';
import { useDebouncedValue } from '../../shared/hooks/useDebouncedValue';
import { Button } from '../../shared/ui/Button';
import { FilterIcon, SortIcon } from '../../shared/ui/Icons';
import { ProductCard } from '../../shared/ui/ProductCard';
import { SearchInput } from '../../shared/ui/SearchInput';
import { Sheet } from '../../shared/ui/Sheets';
import { ProductCardSkeleton } from '../../shared/ui/Skeleton';
import { StateScreen } from '../../shared/ui/StateScreen';

const sortLabels: Record<string, string> = { popular: 'Популярні', newest: 'Спочатку нові', price_asc: 'Ціна: від нижчої', price_desc: 'Ціна: від вищої', discount: 'Найбільша знижка' };
const filterKeys = ['category','brand','color','size','min_price','max_price','only_available','sale','new'] as const;

function FilterSheet({ open, onClose, meta, params, onApply }: { open: boolean; onClose: () => void; meta: CatalogMeta | undefined; params: URLSearchParams; onApply: (params: URLSearchParams) => void }) {
  const [draft, setDraft] = useState(() => new URLSearchParams(params));
  useEffect(() => { if (open) setDraft(new URLSearchParams(params)); }, [open, params]);
  const toggle = (key: string, value: string) => { const next = new URLSearchParams(draft); if (next.get(key) === value) next.delete(key); else next.set(key, value); setDraft(next); };
  const checkbox = (key: string) => { const next = new URLSearchParams(draft); if (next.get(key) === 'true') next.delete(key); else next.set(key, 'true'); setDraft(next); };
  return <Sheet open={open} title="Фільтри" onClose={onClose} footer={<div className="sheet-actions"><Button variant="secondary" onClick={() => setDraft(new URLSearchParams())}>Очистити</Button><Button onClick={() => onApply(draft)}>Показати товари</Button></div>}><div className="filter-group"><h3>Категорія</h3><div className="choice-list">{meta?.categories.map((item) => <button type="button" key={item.id} className={draft.get('category') === item.slug ? 'choice choice--active' : 'choice'} onClick={() => toggle('category', item.slug)}>{item.name}</button>)}</div></div><div className="filter-group"><h3>Бренд</h3><div className="choice-list">{meta?.brands.map((item) => <button type="button" key={item.id} className={draft.get('brand') === item.slug ? 'choice choice--active' : 'choice'} onClick={() => toggle('brand', item.slug)}>{item.name}</button>)}</div></div><div className="filter-group"><h3>Колір</h3><div className="color-filter-list">{meta?.colors.map((item) => <button type="button" key={item.code} className={draft.get('color') === item.code ? 'color-filter color-filter--active' : 'color-filter'} onClick={() => toggle('color', item.code)}><span style={{background:item.hex_value || 'var(--color-border)'}}/>{item.name}</button>)}</div></div><div className="filter-group"><h3>Розмір</h3><div className="choice-list choice-list--compact">{meta?.sizes.map((item) => <button type="button" key={item.code} className={draft.get('size') === item.code ? 'choice choice--active' : 'choice'} onClick={() => toggle('size', item.code)}>{item.name}</button>)}</div></div><div className="filter-group"><h3>Ціна</h3><div className="price-range"><input inputMode="numeric" placeholder="Від" value={draft.get('min_price') || ''} onChange={(event) => { const next = new URLSearchParams(draft); event.target.value ? next.set('min_price', event.target.value) : next.delete('min_price'); setDraft(next); }}/><input inputMode="numeric" placeholder="До" value={draft.get('max_price') || ''} onChange={(event) => { const next = new URLSearchParams(draft); event.target.value ? next.set('max_price', event.target.value) : next.delete('max_price'); setDraft(next); }}/></div></div><div className="filter-switches"><label><input type="checkbox" checked={draft.get('only_available') === 'true'} onChange={() => checkbox('only_available')}/><span>Лише в наявності</span></label><label><input type="checkbox" checked={draft.get('sale') === 'true'} onChange={() => checkbox('sale')}/><span>Зі знижкою</span></label><label><input type="checkbox" checked={draft.get('new') === 'true'} onChange={() => checkbox('new')}/><span>Новинки</span></label></div></Sheet>;
}

export function CatalogPage() {
  const [params, setParams] = useSearchParams();
  const [search, setSearch] = useState(params.get('search') || '');
  const debouncedSearch = useDebouncedValue(search, 350);
  const [filterOpen, setFilterOpen] = useState(false);
  const [sortOpen, setSortOpen] = useState(false);
  const restored = useRef(false);
  const metaQuery = useQuery({ queryKey: ['catalog-meta'], queryFn: catalogApi.meta, staleTime: 300_000 });
  useEffect(() => { const next = new URLSearchParams(params); if (debouncedSearch.trim().length >= 2) next.set('search', debouncedSearch.trim()); else next.delete('search'); if (next.toString() !== params.toString()) setParams(next, { replace: true }); }, [debouncedSearch, params, setParams]);
  const stableParams = useMemo(() => { const next = new URLSearchParams(params); next.delete('page'); return next; }, [params]);
  const productsQuery = useInfiniteQuery({ queryKey: ['products', stableParams.toString()], initialPageParam: 1, queryFn: ({ pageParam }) => { const query = new URLSearchParams(stableParams); query.set('page', String(pageParam)); query.set('limit', '20'); return catalogApi.products(query); }, getNextPageParam: (last) => last.pagination.has_next ? last.pagination.page + 1 : undefined, staleTime: 60_000 });
  const products = productsQuery.data?.pages.flatMap((page) => page.items) || [];
  useEffect(() => { if (!restored.current && products.length) { const saved = Number(sessionStorage.getItem('catalog-scroll') || '0'); if (saved > 0) requestAnimationFrame(() => scrollAppTo(saved, 'auto')); restored.current = true; } }, [products.length]);
  const applyFilters = (next: URLSearchParams) => { if (search.trim().length >= 2) next.set('search', search.trim()); const sort = params.get('sort'); if (sort) next.set('sort', sort); setParams(next); setFilterOpen(false); scrollAppTo(0, 'auto'); };
  const removeFilter = (key: string) => { const next = new URLSearchParams(params); next.delete(key); setParams(next); };
  const count = countActiveCatalogFilters(params);
  return <main className="page catalog-page"><header className="catalog-header"><div><p className="page-kicker">Колекція</p><h1>Каталог</h1></div><p className="catalog-header__count">{productsQuery.data?.pages[0].pagination.total ?? 0} товарів</p></header><SearchInput value={search} onChange={setSearch}/><div className="catalog-toolbar"><button type="button" onClick={() => setFilterOpen(true)}><FilterIcon size={19}/>Фільтри{count ? <span>{count}</span> : null}</button><button type="button" onClick={() => setSortOpen(true)}><SortIcon size={19}/>{sortLabels[params.get('sort') || 'popular']}</button></div>{count ? <div className="active-filters">{filterKeys.map((key) => params.has(key) ? <button key={key} onClick={() => removeFilter(key)}>{key === 'only_available' ? 'В наявності' : key === 'sale' ? 'Знижки' : key === 'new' ? 'Новинки' : params.get(key)} <span>×</span></button> : null)}<button className="active-filters__clear" onClick={() => { const next = new URLSearchParams(); if (params.get('search')) next.set('search', params.get('search')!); setParams(next); }}>Очистити</button></div> : null}{productsQuery.isLoading ? <div className="product-grid">{Array.from({length:8},(_,i)=><ProductCardSkeleton key={i}/>)}</div> : productsQuery.isError ? <StateScreen title="Каталог недоступний" description="Не вдалося отримати товари." actionLabel="Повторити" onAction={() => productsQuery.refetch()}/> : products.length === 0 ? <StateScreen title="Нічого не знайдено" description="Змініть пошук або очистьте частину фільтрів." actionLabel="Очистити фільтри" onAction={() => setParams(new URLSearchParams())}/> : <><div className="product-grid">{products.map((product) => <ProductCard key={product.id} product={product} onOpen={() => sessionStorage.setItem('catalog-scroll', String(readScrollTop()))}/>)}</div>{productsQuery.hasNextPage ? <div className="load-more"><Button variant="secondary" loading={productsQuery.isFetchingNextPage} onClick={() => productsQuery.fetchNextPage()}>Показати ще</Button></div> : null}</>}<FilterSheet open={filterOpen} onClose={() => setFilterOpen(false)} meta={metaQuery.data} params={params} onApply={applyFilters}/><Sheet open={sortOpen} title="Сортування" onClose={() => setSortOpen(false)}><div className="sort-list">{Object.entries(sortLabels).map(([value,label]) => <button type="button" key={value} className={params.get('sort') === value || (!params.get('sort') && value === 'popular') ? 'sort-option sort-option--active' : 'sort-option'} onClick={() => { const next = new URLSearchParams(params); value === 'popular' ? next.delete('sort') : next.set('sort', value); setParams(next); setSortOpen(false); }}>{label}</button>)}</div></Sheet></main>;
}
